import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { ITriviaResult, useDatabase } from "@/src/sqlHook";
import { useEffect, useState } from "react";
import { useDebounce } from "@/src/debounceHook";

export default function Home() {
	const db = useDatabase();

	const [search, setSearch] = useState("");
	const searchDebounced = useDebounce(search, 500);
	const [state, setState] = useState<{
		lastSearch: string;
		results: ITriviaResult[];
	}>({ lastSearch: "", results: [] });

	useEffect(() => {
		if (!db.initialized) return;
		if (state.lastSearch === searchDebounced) return;

		const list = db.getResults(searchDebounced);
		setState({
			lastSearch: searchDebounced,
			results: list,
		});
	}, [db, state, searchDebounced]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1>Tower Trivia Search</h1>
				<p>Start typing the question to show results.</p>
				<input
					type="text"
					className={styles.search}
					onChange={(e) => setSearch(e.target.value)}
					value={search}
				/>

				<div className={styles.cont}>
					{state.results.map((result) => (
						<div key={result.id} className={styles.trivia}>
							<div className={styles.question}>
								{result.question}
							</div>
							<div className={styles.answers}>
								<div className={styles.correct}>
									{result.correctAnswer}
								</div>
								{result.incorrectAnswers.map((answer) => (
									<div
										className={styles.incorrect}
										key={answer}
									>
										{answer}
									</div>
								))}
							</div>
						</div>
					))}
				</div>
			</main>
		</>
	);
}
